/-
Copyright (c) 2026 CompPoly Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Valerii Huhnin
-/

import CompPoly.LinearAlgebra.PolynomialMatrix.Shifted

/-!
# Row Span for Polynomial Matrices
-/

namespace CompPoly

namespace PolynomialMatrix

variable {F : Type*}

/-- Polynomial linear combination of matrix rows. -/
def rowLinearCombination [Semiring F] [BEq F] [LawfulBEq F]
    (coeffs : Array (CPolynomial F)) (M : PolynomialMatrix F) :
    PolynomialRow F :=
  (List.range M.size).foldl
    (fun acc i ↦
      rowAdd acc
        (rowScalePolynomial (coeffs.getD i 0) (M.getD i #[])))
    (zeroRow (MatrixWidth M))

/-- Row module generated by the matrix rows. -/
def RowSpan [Semiring F] [BEq F] [LawfulBEq F]
    (M : PolynomialMatrix F) : Set (PolynomialRow F) :=
  { row | ∃ coeffs : Array (CPolynomial F),
      coeffs.size = M.size ∧ row = rowLinearCombination coeffs M }

/-- Every stored row belongs to its matrix row span. -/
theorem matrix_row_mem_rowSpan [Semiring F] [BEq F] [LawfulBEq F]
    [DecidableEq F]
    {M : PolynomialMatrix F} {row : PolynomialRow F}
    (hrow : row ∈ MatrixRows M) :
    row ∈ RowSpan M := by
  sorry

/-- Row span extensional equality. -/
def RowSpanEq [Semiring F] [BEq F] [LawfulBEq F]
    (A B : PolynomialMatrix F) : Prop :=
  RowSpan A = RowSpan B

end PolynomialMatrix

end CompPoly
