/-
Copyright (c) 2026 CompPoly Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Valerii Huhnin
-/

import CompPolyBench.Common
import CompPoly.Multivariate.CMvPolynomial

/-!
# Multivariate Benchmarks
-/

open CompPoly

namespace CompPolyBench

/-- Benchmark group metadata for `CompPoly.Multivariate.CMvPolynomial`. -/
def multivariateGroupInfos : List BenchGroupInfo := [
  ⟨"multivariate-dense-babybear", "Multivariate dense evaluation (BabyBear)"⟩,
  ⟨"multivariate-sparse-babybear", "Multivariate sparse evaluation (BabyBear)"⟩,
  ⟨"multivariate-dense-goldilocks", "Multivariate dense evaluation (Goldilocks)"⟩,
  ⟨"multivariate-sparse-goldilocks", "Multivariate sparse evaluation (Goldilocks)"⟩
]

/-- Number of variables used by multivariate evaluation benchmarks. -/
private def multivariateVars : Nat := 5

/-- Exponents generated by multivariate benchmarks are reduced modulo this value. -/
private def multivariateExponentMod : Nat := 16

/-- Number of generated coefficient slots for multivariate evaluation benchmarks. -/
private def multivariateTermSlots : Nat := 512

/-- Number of evaluation points used by multivariate evaluation benchmarks. -/
private def multivariatePointCount : Nat := 32

/-- Input-shape label for dense multivariate benchmarks. -/
private def multivariateDenseShape : String :=
  s!"{multivariateVars} vars, {multivariateTermSlots} generated terms, exponent<" ++
    s!"{multivariateExponentMod}, dense coeffs, {multivariatePointCount} points"

/-- Input-shape label for sparse multivariate benchmarks. -/
private def multivariateSparseShape : String :=
  s!"{multivariateVars} vars, {multivariateTermSlots} generated terms, exponent<" ++
    s!"{multivariateExponentMod}, one nonzero per 16 coeffs, {multivariatePointCount} points"

/-- Build a computable multivariate polynomial from generated coefficients. -/
private def buildCMvPolynomial {R : Type*} [CommSemiring R] [BEq R] [LawfulBEq R]
    (terms : Array R) : CPoly.CMvPolynomial multivariateVars R :=
  Id.run do
    let mut p : CPoly.CMvPolynomial multivariateVars R := 0
    for i in [0:terms.size] do
      let m : CPoly.CMvMonomial multivariateVars := Vector.ofFn fun j =>
        (i / (j.val + 1)) % multivariateExponentMod
      p := p + CPoly.CMvPolynomial.monomial m (terms.getD i 0)
    pure p

/-- Benchmark dense multivariate evaluation over a generic prime `ZMod` field. -/
private def runDenseMultivariateZMod (modulus : Nat) [Fact (Nat.Prime modulus)]
    (key nameSuffix fieldName fieldTitle : String) (gen : StdGen) :
    IO (BenchGroup × StdGen) := do
  let (terms, gen) := (zmodArray modulus multivariateTermSlots false).run gen
  let (points, gen) := (zmodArray modulus (multivariateVars * multivariatePointCount) false).run gen
  let poly := buildCMvPolynomial terms
  let evalPoint (offset : Nat) : Fin multivariateVars → ZMod modulus :=
    fun j => points.getD ((offset + j.val) % points.size) 0
  let denseEval ← runTimed
    ("multivariate-dense-eval-" ++ nameSuffix) "CMvPolynomial" "eval" fieldName
    multivariateDenseShape warmupIterations measuredIterations
    (fun i => CPoly.CMvPolynomial.eval (evalPoint (i % multivariatePointCount)) poly)
    checksumZMod
  let denseHorner ← runTimed
    ("multivariate-dense-horner-" ++ nameSuffix) "CMvPolynomial" "evalHorner" fieldName
    multivariateDenseShape warmupIterations measuredIterations
    (fun i => CPoly.CMvPolynomial.evalHorner (evalPoint (i % multivariatePointCount)) poly)
    checksumZMod
  pure ({
    groupKey := key,
    title := "Multivariate dense evaluation (" ++ fieldTitle ++ ")",
    records := #[denseEval, denseHorner]
  }, gen)

/-- Benchmark sparse multivariate evaluation over a generic prime `ZMod` field. -/
private def runSparseMultivariateZMod (modulus : Nat) [Fact (Nat.Prime modulus)]
    (key nameSuffix fieldName fieldTitle : String) (gen : StdGen) :
    IO (BenchGroup × StdGen) := do
  let (terms, gen) := (zmodArrayWithStride modulus multivariateTermSlots 16).run gen
  let (points, gen) := (zmodArray modulus (multivariateVars * multivariatePointCount) false).run gen
  let poly := buildCMvPolynomial terms
  let evalPoint (offset : Nat) : Fin multivariateVars → ZMod modulus :=
    fun j => points.getD ((offset + j.val) % points.size) 0
  let sparseEval ← runTimed
    ("multivariate-sparse-eval-" ++ nameSuffix) "CMvPolynomial" "eval" fieldName
    multivariateSparseShape warmupIterations measuredIterations
    (fun i => CPoly.CMvPolynomial.eval (evalPoint (i % multivariatePointCount)) poly)
    checksumZMod
  let sparseHorner ← runTimed
    ("multivariate-sparse-horner-" ++ nameSuffix) "CMvPolynomial" "evalHorner" fieldName
    multivariateSparseShape warmupIterations measuredIterations
    (fun i => CPoly.CMvPolynomial.evalHorner (evalPoint (i % multivariatePointCount)) poly)
    checksumZMod
  pure ({
    groupKey := key,
    title := "Multivariate sparse evaluation (" ++ fieldTitle ++ ")",
    records := #[sparseEval, sparseHorner]
  }, gen)

/-- Run BabyBear dense multivariate evaluation benchmarks. -/
private def runBabyBearMultivariateDense (gen : StdGen) : IO (BenchGroup × StdGen) := do
  let (terms, gen) := (babyBearArray multivariateTermSlots false).run gen
  let (points, gen) := (babyBearPoints (multivariateVars * multivariatePointCount)).run gen
  let poly := buildCMvPolynomial terms
  let evalPoint (offset : Nat) : Fin multivariateVars → BabyBear.Field :=
    fun j => points.getD ((offset + j.val) % points.size) 0
  let denseEval ← runTimed
    "multivariate-dense-eval" "CMvPolynomial" "eval" "BabyBear.Field"
    multivariateDenseShape warmupIterations measuredIterations
    (fun i => CPoly.CMvPolynomial.eval (evalPoint (i % multivariatePointCount)) poly)
    checksumBabyBear
  let denseHorner ← runTimed
    "multivariate-dense-horner" "CMvPolynomial" "evalHorner" "BabyBear.Field"
    multivariateDenseShape warmupIterations measuredIterations
    (fun i => CPoly.CMvPolynomial.evalHorner (evalPoint (i % multivariatePointCount)) poly)
    checksumBabyBear
  pure ({
    groupKey := "multivariate-dense-babybear",
    title := "Multivariate dense evaluation (BabyBear)",
    records := #[denseEval, denseHorner]
  }, gen)

/-- Run BabyBear sparse multivariate evaluation benchmarks. -/
private def runBabyBearMultivariateSparse (gen : StdGen) : IO (BenchGroup × StdGen) := do
  let (terms, gen) := (babyBearArrayWithStride multivariateTermSlots 16).run gen
  let (points, gen) := (babyBearPoints (multivariateVars * multivariatePointCount)).run gen
  let poly := buildCMvPolynomial terms
  let evalPoint (offset : Nat) : Fin multivariateVars → BabyBear.Field :=
    fun j => points.getD ((offset + j.val) % points.size) 0
  let sparseEval ← runTimed
    "multivariate-sparse-eval" "CMvPolynomial" "eval" "BabyBear.Field"
    multivariateSparseShape warmupIterations measuredIterations
    (fun i => CPoly.CMvPolynomial.eval (evalPoint (i % multivariatePointCount)) poly)
    checksumBabyBear
  let sparseHorner ← runTimed
    "multivariate-sparse-horner" "CMvPolynomial" "evalHorner" "BabyBear.Field"
    multivariateSparseShape warmupIterations measuredIterations
    (fun i => CPoly.CMvPolynomial.evalHorner (evalPoint (i % multivariatePointCount)) poly)
    checksumBabyBear
  pure ({
    groupKey := "multivariate-sparse-babybear",
    title := "Multivariate sparse evaluation (BabyBear)",
    records := #[sparseEval, sparseHorner]
  }, gen)

/-- Run Goldilocks dense multivariate evaluation benchmarks. -/
private def runGoldilocksMultivariateDense (gen : StdGen) : IO (BenchGroup × StdGen) := do
  runDenseMultivariateZMod Goldilocks.fieldSize
    "multivariate-dense-goldilocks" "goldilocks" "Goldilocks.Field" "Goldilocks" gen

/-- Run Goldilocks sparse multivariate evaluation benchmarks. -/
private def runGoldilocksMultivariateSparse (gen : StdGen) : IO (BenchGroup × StdGen) := do
  runSparseMultivariateZMod Goldilocks.fieldSize
    "multivariate-sparse-goldilocks" "goldilocks" "Goldilocks.Field" "Goldilocks" gen

/-- Runnable multivariate benchmark tasks. -/
def multivariateTasks : List BenchTask := [
  BenchTask.fromGroupRunner
    ⟨"multivariate-dense-babybear", "Multivariate dense evaluation (BabyBear)"⟩
    runBabyBearMultivariateDense,
  BenchTask.fromGroupRunner
    ⟨"multivariate-sparse-babybear", "Multivariate sparse evaluation (BabyBear)"⟩
    runBabyBearMultivariateSparse,
  BenchTask.fromGroupRunner
    ⟨"multivariate-dense-goldilocks", "Multivariate dense evaluation (Goldilocks)"⟩
    runGoldilocksMultivariateDense,
  BenchTask.fromGroupRunner
    ⟨"multivariate-sparse-goldilocks", "Multivariate sparse evaluation (Goldilocks)"⟩
    runGoldilocksMultivariateSparse
]

/-- Run sparse and dense multivariate evaluation benchmarks. -/
def runMultivariate (selection : BenchSelection) (gen : StdGen) :
    IO (Array BenchGroup × StdGen) := do
  runSelectedTasks multivariateTasks selection gen

end CompPolyBench
