/-
Copyright (c) 2026 CompPoly Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Valerii Huhnin
-/

import CompPolyBench.Common
import CompPoly.Multivariate.CMvPolynomial

/-!
# Multivariate Benchmarks
-/

open CompPoly

namespace CompPolyBench

/-- Number of variables used by multivariate evaluation benchmarks. -/
private def multivariateVars : Nat := 5

/-- Exponents generated by multivariate benchmarks are reduced modulo this value. -/
private def multivariateExponentMod : Nat := 16

/-- Number of generated coefficient slots for multivariate evaluation benchmarks. -/
private def multivariateTermSlots : Nat := 512

/-- Number of evaluation points used by multivariate evaluation benchmarks. -/
private def multivariatePointCount : Nat := 32

/-- Input-shape label for dense multivariate benchmarks. -/
private def multivariateDenseShape : String :=
  s!"{multivariateVars} vars, {multivariateTermSlots} generated terms, exponent<" ++
    s!"{multivariateExponentMod}, dense coeffs, {multivariatePointCount} points"

/-- Input-shape label for sparse multivariate benchmarks. -/
private def multivariateSparseShape : String :=
  s!"{multivariateVars} vars, {multivariateTermSlots} generated terms, exponent<" ++
    s!"{multivariateExponentMod}, one nonzero per 16 coeffs, {multivariatePointCount} points"

/-- Build a computable multivariate polynomial from generated coefficients. -/
private def buildCMvPolynomial {R : Type*} [CommSemiring R] [BEq R] [LawfulBEq R]
    (terms : Array R) : CPoly.CMvPolynomial multivariateVars R :=
  Id.run do
    let mut p : CPoly.CMvPolynomial multivariateVars R := 0
    for i in [0:terms.size] do
      let m : CPoly.CMvMonomial multivariateVars := Vector.ofFn fun j =>
        (i / (j.val + 1)) % multivariateExponentMod
      p := p + CPoly.CMvPolynomial.monomial m (terms.getD i 0)
    pure p

/-- Benchmark dense and sparse multivariate evaluation over a generic prime `ZMod` field. -/
private def runMultivariateZMod (modulus : Nat) [Fact (Nat.Prime modulus)]
    (nameSuffix fieldName : String) (gen : StdGen) : IO (Array BenchGroup × StdGen) := do
  let (denseTerms, gen) := (zmodArray modulus multivariateTermSlots false).run gen
  let (sparseTerms, gen) := (zmodArrayWithStride modulus multivariateTermSlots 16).run gen
  let (points, gen) := (zmodArray modulus (multivariateVars * multivariatePointCount) false).run gen
  let densePoly := buildCMvPolynomial denseTerms
  let sparsePoly := buildCMvPolynomial sparseTerms
  let evalPoint (offset : Nat) : Fin multivariateVars → ZMod modulus :=
    fun j => points.getD ((offset + j.val) % points.size) 0
  let denseEval ← runTimed
    ("multivariate-dense-eval-" ++ nameSuffix) "CMvPolynomial" "eval" fieldName
    multivariateDenseShape warmupIterations measuredIterations
    (fun i => CPoly.CMvPolynomial.eval (evalPoint (i % multivariatePointCount)) densePoly)
    checksumZMod
  let denseHorner ← runTimed
    ("multivariate-dense-horner-" ++ nameSuffix) "CMvPolynomial" "evalHorner" fieldName
    multivariateDenseShape warmupIterations measuredIterations
    (fun i => CPoly.CMvPolynomial.evalHorner (evalPoint (i % multivariatePointCount)) densePoly)
    checksumZMod
  let sparseEval ← runTimed
    ("multivariate-sparse-eval-" ++ nameSuffix) "CMvPolynomial" "eval" fieldName
    multivariateSparseShape warmupIterations measuredIterations
    (fun i => CPoly.CMvPolynomial.eval (evalPoint (i % multivariatePointCount)) sparsePoly)
    checksumZMod
  let sparseHorner ← runTimed
    ("multivariate-sparse-horner-" ++ nameSuffix) "CMvPolynomial" "evalHorner" fieldName
    multivariateSparseShape warmupIterations measuredIterations
    (fun i => CPoly.CMvPolynomial.evalHorner (evalPoint (i % multivariatePointCount)) sparsePoly)
    checksumZMod
  pure (#[{
    title := fieldName ++ " multivariate dense evaluation"
    records := #[denseEval, denseHorner]
  }, {
    title := fieldName ++ " multivariate sparse evaluation"
    records := #[sparseEval, sparseHorner]
  }], gen)

/-- Run sparse and dense multivariate evaluation benchmarks. -/
def runMultivariate (gen : StdGen) : IO (Array BenchGroup × StdGen) := do
  let (sparseTerms, gen) := (babyBearArrayWithStride multivariateTermSlots 16).run gen
  let (denseTerms, gen) := (babyBearArray multivariateTermSlots false).run gen
  let (points, gen) := (babyBearPoints (multivariateVars * multivariatePointCount)).run gen
  let sparsePoly := buildCMvPolynomial sparseTerms
  let densePoly := buildCMvPolynomial denseTerms
  let evalPoint (offset : Nat) : Fin multivariateVars → BabyBear.Field :=
    fun j => points.getD ((offset + j.val) % points.size) 0
  let mut groups := #[]
  let denseEval ← runTimed
    "multivariate-dense-eval" "CMvPolynomial" "eval" "BabyBear.Field"
    multivariateDenseShape warmupIterations measuredIterations
    (fun i => CPoly.CMvPolynomial.eval (evalPoint (i % multivariatePointCount)) densePoly)
    checksumBabyBear
  let denseHorner ← runTimed
    "multivariate-dense-horner" "CMvPolynomial" "evalHorner" "BabyBear.Field"
    multivariateDenseShape warmupIterations measuredIterations
    (fun i => CPoly.CMvPolynomial.evalHorner (evalPoint (i % multivariatePointCount)) densePoly)
    checksumBabyBear
  groups := groups.push {
    title := "BabyBear multivariate dense evaluation"
    records := #[denseEval, denseHorner]
  }
  let sparseEval ← runTimed
    "multivariate-sparse-eval" "CMvPolynomial" "eval" "BabyBear.Field"
    multivariateSparseShape warmupIterations measuredIterations
    (fun i => CPoly.CMvPolynomial.eval (evalPoint (i % multivariatePointCount)) sparsePoly)
    checksumBabyBear
  let sparseHorner ← runTimed
    "multivariate-sparse-horner" "CMvPolynomial" "evalHorner" "BabyBear.Field"
    multivariateSparseShape warmupIterations measuredIterations
    (fun i => CPoly.CMvPolynomial.evalHorner (evalPoint (i % multivariatePointCount)) sparsePoly)
    checksumBabyBear
  groups := groups.push {
    title := "BabyBear multivariate sparse evaluation"
    records := #[sparseEval, sparseHorner]
  }
  let (goldilocksGroups, gen) ← runMultivariateZMod
    Goldilocks.fieldSize "goldilocks" "Goldilocks.Field" gen
  groups := appendGroups groups goldilocksGroups
  pure (groups, gen)

end CompPolyBench
