/-
Copyright (c) 2026 CompPoly. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: CompPoly Contributors
-/
import Mathlib.RingTheory.AdjoinRoot
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.Algebra.Polynomial.Div

/-!
# Negacyclic / Incomplete NTT Convolution

CompPoly's main NTT (`CompPoly.CPolynomial.NTT.FastMul.fastMulImpl_eq_mul`) is a
*cyclic*, radix-2 transform: it pads to a power-of-two length, evaluates over a
domain generated by a primitive `2 ^ logN`-th root of unity, and recovers the
full product via a cyclic convolution.

ML-KEM, however, multiplies in the *negacyclic* ring `R[X] / (X^n + 1)` with
`R = ZMod 3329`, `n = 256`. Over `ZMod 3329` there is a primitive `256`-th root
of unity but no `512`-th root, so `X^256 + 1` does not split into linear factors.
Instead it factors into `128` pairwise-coprime *quadratics* `X^2 - ζ_i`, and
ML-KEM's "incomplete NTT" is the Chinese-Remainder isomorphism

  `R[X] / (X^n + 1) ≅ ∏_i R[X] / (X^2 - ζ_i)`,

under which polynomial multiplication becomes the pointwise `basemul` on the
degree-`< 2` components.  This file supplies the algebra that CompPoly's cyclic
NTT lacks.

## Main definitions

* `quadPoly ζ` — the quadratic modulus `X^2 - C ζ` of a single incomplete-NTT
  component.
* `negaPoly n` — the negacyclic modulus `X^n + 1`.
* `incompleteNTT` — the abstract CRT ring isomorphism
  `R[X] / (⨅ i, (f i)) ≃+* ∏ i, R[X] / (f i)` attached to a pairwise-coprime
  family of polynomial moduli `f`.
* `incompleteNTTOfModulus` — `incompleteNTT` specialised to a known product
  modulus `q` (for ML-KEM, `q = X^n + 1`).

## Main results

* `basemul_adjoinRoot` / `basemul_mod` — the degree-2 `basemul` formula
  `(a₀ + a₁ X)(b₀ + b₁ X) ≡ (a₀ b₀ + ζ a₁ b₁) + (a₀ b₁ + a₁ b₀) X (mod X^2 - ζ)`,
  ML-KEM's `_poly_basemul`, in `AdjoinRoot` and in coefficient form respectively.
* `negacyclic_modByMonic_coeff` / `negacyclic_mul_coeff` — the negacyclic
  convolution coefficient formula in `R[X] / (X^n + 1)`: the `X^n ≡ -1` fold
  `c_k = (Σ_{i+j=k} a_i b_j) − (Σ_{i+j=k+n} a_i b_j)`.
* `incompleteNTT_map_mul` / `incompleteNTTOfModulus_map_mul` — the CRT
  isomorphism respects multiplication (`map_mul`): "the NTT turns convolution
  into pointwise multiplication".
* `incompleteNTT_component_basemul` — the bridge tying the two halves together.
  On a single component `R[X] / (X^2 - C ζ)`, the pointwise product of two
  degree-`≤ 1` elements is the `basemul` formula, so the informal reading
  "pointwise = basemul" is a theorem, not a slogan.

## Implementation notes

Both `basemul_mod` and `negacyclic_modByMonic_coeff` split on
`subsingleton_or_nontrivial R`. Over the zero ring every polynomial collapses to
`0` and `Subsingleton.elim` closes the goal; over a nontrivial ring the modulus
has its expected degree, so `modByMonic_eq_self_iff` and
`modByMonic_eq_zero_iff_dvd` apply.

The *concrete* factorization `X^256 + 1 = ∏_{i<128} (X^2 - ζ_i)` over `ZMod 3329`,
and the pairwise coprimality of those quadratics, is genuine cyclotomic algebra
over a specific finite field and is out of scope here. It is exactly the `hcop`
and `hfact` hypotheses of `incompleteNTT` / `incompleteNTTOfModulus`; discharging
them for the ML-KEM parameters `(3329, 256)` is the remaining concrete step.

## References

The negacyclic ring `ℤ_q[X] / (X^256 + 1)` and the incomplete NTT are specified
in the ML-KEM standard [FIPS 203][fips203]. The Chinese Remainder isomorphism
underlying `incompleteNTT` is Mathlib's `Ideal.quotientInfRingEquivPiQuotient`.

* [National Institute of Standards and Technology, *Module-Lattice-Based
  Key-Encapsulation Mechanism Standard*, FIPS 203, 2024][fips203]
-/

open Polynomial

namespace CompPoly
namespace CPolynomial
namespace NTT
namespace Negacyclic

/-! ### (1) The degree-2 `basemul` formula -/

section Basemul

variable {R : Type*} [CommRing R]

/-- The defining polynomial `X^2 - C ζ` of a single incomplete-NTT component. -/
noncomputable def quadPoly (ζ : R) : R[X] := X ^ 2 - C ζ

/-- The component modulus `quadPoly ζ = X^2 - C ζ` is monic. -/
theorem quadPoly_monic (ζ : R) : (quadPoly ζ).Monic := by
  unfold quadPoly
  exact monic_X_pow_sub_C ζ two_ne_zero

/-- The image of `X` in `AdjoinRoot (X^2 - C ζ)` squares to `ζ`.  This is the
single algebraic relation `root^2 = ζ` that drives the `basemul` formula. -/
theorem root_sq (ζ : R) :
    (AdjoinRoot.root (quadPoly ζ)) ^ 2 = algebraMap R (AdjoinRoot (quadPoly ζ)) ζ := by
  have h : AdjoinRoot.mk (quadPoly ζ) (quadPoly ζ) = 0 := AdjoinRoot.mk_self
  unfold quadPoly at h
  rw [map_sub, map_pow, AdjoinRoot.mk_X, AdjoinRoot.mk_C] at h
  rw [AdjoinRoot.algebraMap_eq]
  rw [sub_eq_zero] at h
  exact h

/--
**ML-KEM `_poly_basemul`** (degree-2 / `AdjoinRoot` form).

In `R[X] / (X^2 - ζ)` (presented as `AdjoinRoot (X^2 - C ζ)`, with `α` the image
of `X`), the product of two degree-`≤ 1` elements is

  `(a₀ + a₁ α)(b₀ + b₁ α) = (a₀ b₀ + ζ a₁ b₁) + (a₀ b₁ + a₁ b₀) α`.

The `α^2 = ζ` fold is the only nonlinear step; everything else is `ring`.
-/
theorem basemul_adjoinRoot (ζ a₀ a₁ b₀ b₁ : R) :
    (algebraMap R (AdjoinRoot (quadPoly ζ)) a₀
        + algebraMap R (AdjoinRoot (quadPoly ζ)) a₁ * AdjoinRoot.root (quadPoly ζ))
      * (algebraMap R (AdjoinRoot (quadPoly ζ)) b₀
        + algebraMap R (AdjoinRoot (quadPoly ζ)) b₁ * AdjoinRoot.root (quadPoly ζ))
      = algebraMap R (AdjoinRoot (quadPoly ζ)) (a₀ * b₀ + ζ * (a₁ * b₁))
        + algebraMap R (AdjoinRoot (quadPoly ζ)) (a₀ * b₁ + a₁ * b₀)
          * AdjoinRoot.root (quadPoly ζ) := by
  set ι : R →+* AdjoinRoot (quadPoly ζ) := algebraMap R (AdjoinRoot (quadPoly ζ))
  set α : AdjoinRoot (quadPoly ζ) := AdjoinRoot.root (quadPoly ζ)
  have hα : α ^ 2 = ι ζ := root_sq ζ
  simp only [map_add, map_mul]
  -- Expand the product and rewrite `α^2` via `hα`.
  have expand :
      (ι a₀ + ι a₁ * α) * (ι b₀ + ι b₁ * α)
        = ι a₀ * ι b₀ + (ι a₁ * ι b₁) * α ^ 2
          + (ι a₀ * ι b₁ + ι a₁ * ι b₀) * α := by ring
  rw [expand, hα]
  ring

/--
**ML-KEM `_poly_basemul`** (`modByMonic` / coefficient form).

If `a = C a₀ + C a₁ * X` and `b = C b₀ + C b₁ * X` are degree-`≤ 1` polynomials,
then their product reduced modulo `X^2 - C ζ` is

  `(C (a₀ b₀ + ζ a₁ b₁)) + (C (a₀ b₁ + a₁ b₀)) * X`.

This is the schoolbook `basemul` on raw coefficients.
-/
theorem basemul_mod (ζ a₀ a₁ b₀ b₁ : R) :
    ((C a₀ + C a₁ * X) * (C b₀ + C b₁ * X)) %ₘ (quadPoly ζ)
      = C (a₀ * b₀ + ζ * (a₁ * b₁)) + C (a₀ * b₁ + a₁ * b₀) * X := by
  classical
  rcases subsingleton_or_nontrivial R with hsub | hntr
  · -- Trivial ring: every polynomial is `0`.
    exact Subsingleton.elim _ _
  · have hmonic : (quadPoly ζ).Monic := quadPoly_monic ζ
    set r : R[X] := C (a₀ * b₀ + ζ * (a₁ * b₁)) + C (a₀ * b₁ + a₁ * b₀) * X with hr
    -- `p - r = (C a₁ * C b₁) * (X^2 - C ζ)` exactly, so `f ∣ (p - r)`.
    have hdvd : (quadPoly ζ) ∣ ((C a₀ + C a₁ * X) * (C b₀ + C b₁ * X) - r) := by
      refine ⟨C a₁ * C b₁, ?_⟩
      unfold quadPoly
      rw [hr]
      simp only [C_mul, C_add]
      ring
    -- `(p - r) %ₘ f = 0`, and `p %ₘ f - r %ₘ f = (p - r) %ₘ f`.
    have hzero : ((C a₀ + C a₁ * X) * (C b₀ + C b₁ * X) - r) %ₘ (quadPoly ζ) = 0 :=
      (modByMonic_eq_zero_iff_dvd hmonic).2 hdvd
    rw [sub_modByMonic] at hzero
    -- `r %ₘ f = r` because `deg r < 2 = deg f`.
    have hdeg : (r : R[X]).degree < (quadPoly ζ).degree := by
      have hr_deg : r.degree ≤ 1 := by
        rw [hr]
        refine (degree_add_le _ _).trans ?_
        simp only [sup_le_iff]
        constructor
        · exact (degree_C_le).trans zero_le_one
        · exact (degree_C_mul_X_le _).trans le_rfl
      have hf_deg : (quadPoly ζ).degree = (2 : ℕ) := by
        unfold quadPoly
        rw [degree_X_pow_sub_C two_pos ζ]
      rw [hf_deg]
      exact lt_of_le_of_lt hr_deg (by norm_num)
    have hrr : r %ₘ (quadPoly ζ) = r := (modByMonic_eq_self_iff hmonic).2 hdeg
    rw [hrr] at hzero
    rw [sub_eq_zero] at hzero
    rw [hzero]

end Basemul

/-! ### (2) The negacyclic convolution coefficient formula -/

section Convolution

variable {R : Type*} [CommRing R]

/-- The negacyclic modulus `X^n + 1`. -/
noncomputable def negaPoly (n : ℕ) : R[X] := X ^ n + 1

/-- The negacyclic modulus `negaPoly n = X^n + 1` is monic when `0 < n`. -/
theorem negaPoly_monic {n : ℕ} (hn : 0 < n) : (negaPoly (R := R) n).Monic := by
  unfold negaPoly
  refine monic_X_pow_add ?_
  refine lt_of_le_of_lt degree_one_le ?_
  exact_mod_cast hn

/-- Low-degree part `∑_{k<n} (coeff k) X^k`. -/
private noncomputable def loPart (p : R[X]) (n : ℕ) : R[X] :=
  ∑ k ∈ Finset.range n, C (p.coeff k) * X ^ k

/-- High-degree part shifted down: `∑_{k<n} (coeff (k+n)) X^k`. -/
private noncomputable def hiPart (p : R[X]) (n : ℕ) : R[X] :=
  ∑ k ∈ Finset.range n, C (p.coeff (k + n)) * X ^ k

private theorem coeff_loPart (p : R[X]) (n d : ℕ) :
    (loPart p n).coeff d = if d < n then p.coeff d else 0 := by
  unfold loPart
  rw [finsetSum_coeff]
  simp only [coeff_C_mul, coeff_X_pow, mul_ite, mul_one, mul_zero, Finset.sum_ite_eq,
    Finset.mem_range]

private theorem coeff_hiPart (p : R[X]) (n d : ℕ) :
    (hiPart p n).coeff d = if d < n then p.coeff (d + n) else 0 := by
  unfold hiPart
  rw [finsetSum_coeff]
  simp only [coeff_C_mul, coeff_X_pow, mul_ite, mul_one, mul_zero, Finset.sum_ite_eq,
    Finset.mem_range]

private theorem bot_lt_n (n : ℕ) : (⊥ : WithBot ℕ) < (n : ℕ) := by
  rw [Nat.cast_withBot]
  exact WithBot.bot_lt_coe n

private theorem degree_loPart_lt (p : R[X]) (n : ℕ) :
    (loPart p n).degree < (n : ℕ) := by
  unfold loPart
  refine lt_of_le_of_lt (degree_sum_le _ _) ?_
  refine (Finset.sup_lt_iff (bot_lt_n n)).2 ?_
  intro k hk
  rw [Finset.mem_range] at hk
  refine lt_of_le_of_lt (degree_C_mul_X_pow_le k _) ?_
  exact_mod_cast hk

private theorem degree_hiPart_lt (p : R[X]) (n : ℕ) :
    (hiPart p n).degree < (n : ℕ) := by
  unfold hiPart
  refine lt_of_le_of_lt (degree_sum_le _ _) ?_
  refine (Finset.sup_lt_iff (bot_lt_n n)).2 ?_
  intro k hk
  rw [Finset.mem_range] at hk
  refine lt_of_le_of_lt (degree_C_mul_X_pow_le k _) ?_
  exact_mod_cast hk

/-- If `p` has degree `< 2n` then `p = loPart + hiPart * X^n` (the high/low split). -/
private theorem split_eq (p : R[X]) {n : ℕ}
    (hp : p.degree < (2 * n : ℕ)) :
    p = loPart p n + hiPart p n * X ^ n := by
  ext d
  rw [coeff_add, coeff_loPart, coeff_mul_X_pow', coeff_hiPart]
  by_cases hdn : d < n
  · simp only [hdn, if_true]
    rw [if_neg (by omega)]
    ring
  · simp only [hdn, if_false]
    rw [if_pos (by omega)]
    by_cases hd2 : d - n < n
    · simp only [hd2, if_true]
      have : d - n + n = d := by omega
      rw [this, zero_add]
    · simp only [hd2, if_false]
      -- both terms vanish: `d ≥ 2n > degree p`, so `p.coeff d = 0`.
      have hge : (2 * n : ℕ) ≤ d := by omega
      have hcast : ((2 * n : ℕ) : WithBot ℕ) ≤ (d : ℕ) := by
        rw [Nat.cast_withBot, Nat.cast_withBot, WithBot.coe_le_coe]; exact hge
      rw [coeff_eq_zero_of_degree_lt (lt_of_lt_of_le hp hcast), zero_add]

/--
**Negacyclic convolution coefficient formula.**

For `p` of degree `< 2n` (in particular `p = a * b` with `deg a, deg b < n`),
the reduction of `p` modulo `X^n + 1` has coefficients given by the `X^n ≡ -1`
fold:

  `(p %ₘ (X^n + 1)).coeff k = p.coeff k − p.coeff (k + n)`   for `k < n`.

(For `k ≥ n` the left-hand side is `0` since the remainder has degree `< n`.)
-/
theorem negacyclic_modByMonic_coeff (p : R[X]) {n : ℕ} (hn : 0 < n)
    (hp : p.degree < (2 * n : ℕ)) {k : ℕ} (hk : k < n) :
    (p %ₘ negaPoly n).coeff k = p.coeff k - p.coeff (k + n) := by
  classical
  rcases subsingleton_or_nontrivial R with hsub | hntr
  · exact Subsingleton.elim _ _
  · have hmonic : (negaPoly (R := R) n).Monic := negaPoly_monic hn
    -- The high/low split, with `lo`, `hi` as opaque local names so that
    -- rewriting the standalone `p` does not touch the parts.
    have hsplit : p = loPart p n + hiPart p n * X ^ n := split_eq p hp
    set lo : R[X] := loPart p n with hlo
    set hi : R[X] := hiPart p n with hhi
    -- The explicit remainder `r = lo - hi`.
    set r : R[X] := lo - hi with hr
    -- `p - r = hi * (X^n + 1)`, so `negaPoly n ∣ (p - r)`.
    have hdvd : (negaPoly (R := R) n) ∣ (p - r) := by
      refine ⟨hi, ?_⟩
      unfold negaPoly
      rw [hr, hsplit]
      ring
    have hzero : (p - r) %ₘ negaPoly n = 0 := (modByMonic_eq_zero_iff_dvd hmonic).2 hdvd
    rw [sub_modByMonic] at hzero
    -- `deg r < n`, hence `r %ₘ (X^n+1) = r`.
    have hdeg : r.degree < (negaPoly (R := R) n).degree := by
      have hr_deg : r.degree < (n : ℕ) := by
        rw [hr, hlo, hhi]
        refine lt_of_le_of_lt (degree_sub_le _ _) ?_
        exact max_lt (degree_loPart_lt p n) (degree_hiPart_lt p n)
      have hf_deg : (negaPoly (R := R) n).degree = (n : ℕ) := by
        unfold negaPoly
        rw [show (1 : R[X]) = C 1 from (map_one C).symm, degree_X_pow_add_C hn]
      rw [hf_deg]; exact hr_deg
    have hrr : r %ₘ negaPoly n = r := (modByMonic_eq_self_iff hmonic).2 hdeg
    rw [hrr, sub_eq_zero] at hzero
    rw [hzero, hr, hlo, hhi, coeff_sub, coeff_loPart, coeff_hiPart, if_pos hk, if_pos hk]

/--
**Negacyclic convolution as an antidiagonal sum.**

Specialising `negacyclic_modByMonic_coeff` to a product `a * b` and unfolding
`Polynomial.coeff_mul`, the `k`-th coefficient of `(a * b) %ₘ (X^n + 1)` for
`k < n` is the explicit negacyclic convolution

  `(Σ_{i+j=k} a_i b_j) − (Σ_{i+j=k+n} a_i b_j)`.

This is exactly what the schoolbook negacyclic convolution computes.
-/
theorem negacyclic_mul_coeff (a b : R[X]) {n : ℕ} (hn : 0 < n)
    (hab : (a * b).degree < (2 * n : ℕ)) {k : ℕ} (hk : k < n) :
    ((a * b) %ₘ negaPoly n).coeff k
      = (∑ ij ∈ Finset.antidiagonal k, a.coeff ij.1 * b.coeff ij.2)
        - (∑ ij ∈ Finset.antidiagonal (k + n), a.coeff ij.1 * b.coeff ij.2) := by
  rw [negacyclic_modByMonic_coeff (a * b) hn hab hk, coeff_mul, coeff_mul]

end Convolution

/-! ### (3) The abstract CRT convolution theorem (incomplete NTT) -/

section CRT

open scoped Function

variable {R : Type*} [CommRing R]

/--
**Incomplete NTT isomorphism (abstract CRT form).**

Given a finite family of polynomials `f : ι → R[X]` that are **pairwise coprime
as ideals** (the hypothesis `hcop`), the Chinese Remainder Theorem yields a ring
isomorphism

  `R[X] / (⨅ i, (f i))  ≅  ∏ i, R[X] / (f i)`.

For ML-KEM this is exactly the incomplete NTT: with `f i = X^2 - ζ_i` the
quadratic factors of `X^n + 1`, the right-hand side is the product over the
degree-`< 2` components on which `basemul` operates.  The concrete factorization
`X^256 + 1 = ∏_{i<128} (X^2 - ζ_i)` over `ZMod 3329` (which would let one rewrite
`⨅ i, (f i)` as `(X^256 + 1)`) is the deferred cyclotomic step; see the module
docstring.
-/
noncomputable def incompleteNTT {ι : Type*} [Finite ι] (f : ι → R[X])
    (hcop : Pairwise (IsCoprime on (fun i => Ideal.span {f i}))) :
    (R[X] ⧸ ⨅ i, Ideal.span {f i}) ≃+* ∀ i, R[X] ⧸ Ideal.span {f i} :=
  Ideal.quotientInfRingEquivPiQuotient (fun i => Ideal.span {f i}) hcop

/--
**Multiplication respects the incomplete-NTT decomposition.**

The incomplete-NTT isomorphism is a *ring* homomorphism, so it carries the
product in `R[X] / (⨅ i, (f i))` to the *pointwise* product of the per-component
images.  This is the abstract statement that "the NTT turns convolution into
pointwise multiplication"; for the quadratic factors `X^2 - ζ_i` that pointwise
operation is the `basemul` formula, as shown by `incompleteNTT_component_basemul`.
-/
theorem incompleteNTT_map_mul {ι : Type*} [Finite ι] (f : ι → R[X])
    (hcop : Pairwise (IsCoprime on (fun i => Ideal.span {f i})))
    (a b : R[X] ⧸ ⨅ i, Ideal.span {f i}) :
    incompleteNTT f hcop (a * b) = incompleteNTT f hcop a * incompleteNTT f hcop b :=
  map_mul (incompleteNTT f hcop) a b

/--
**Incomplete NTT specialised to a known modulus `q`.**

If, in addition, the pairwise-coprime factors multiply out (intersect) to a
single principal ideal `(q)` — the hypothesis `hfact : (⨅ i, (f i)) = (q)`,
which for ML-KEM is `q = X^n + 1` — then the incomplete NTT becomes an
isomorphism out of the negacyclic ring itself:

  `R[X] / (q)  ≅  ∏ i, R[X] / (f i)`.
-/
noncomputable def incompleteNTTOfModulus {ι : Type*} [Finite ι] (f : ι → R[X]) (q : R[X])
    (hcop : Pairwise (IsCoprime on (fun i => Ideal.span {f i})))
    (hfact : (⨅ i, Ideal.span {f i}) = Ideal.span {q}) :
    (R[X] ⧸ Ideal.span {q}) ≃+* ∀ i, R[X] ⧸ Ideal.span {f i} :=
  (Ideal.quotEquivOfEq hfact.symm).trans (incompleteNTT f hcop)

/-- The modulus-specialised incomplete NTT also respects multiplication. -/
theorem incompleteNTTOfModulus_map_mul {ι : Type*} [Finite ι] (f : ι → R[X]) (q : R[X])
    (hcop : Pairwise (IsCoprime on (fun i => Ideal.span {f i})))
    (hfact : (⨅ i, Ideal.span {f i}) = Ideal.span {q})
    (a b : R[X] ⧸ Ideal.span {q}) :
    incompleteNTTOfModulus f q hcop hfact (a * b)
      = incompleteNTTOfModulus f q hcop hfact a * incompleteNTTOfModulus f q hcop hfact b :=
  map_mul (incompleteNTTOfModulus f q hcop hfact) a b

/--
**Two-factor incomplete NTT.**

For two coprime polynomial moduli `f₀, f₁`, the CRT isomorphism

  `R[X] / (f₀) ⊓ (f₁)  ≅  (R[X] / (f₀)) × (R[X] / (f₁))`

respects multiplication.  Iterating this is how the incomplete NTT is built in
practice; the per-pair quotients are the `R[X] / (X^2 - ζ_i)` on which `basemul`
acts.
-/
theorem incompleteNTT_two_map_mul (f₀ f₁ : R[X])
    (hcop : IsCoprime (Ideal.span {f₀}) (Ideal.span {f₁}))
    (a b : R[X] ⧸ (Ideal.span {f₀} ⊓ Ideal.span {f₁})) :
    Ideal.quotientInfEquivQuotientProd _ _ hcop (a * b)
      = Ideal.quotientInfEquivQuotientProd _ _ hcop a
        * Ideal.quotientInfEquivQuotientProd _ _ hcop b :=
  map_mul (Ideal.quotientInfEquivQuotientProd _ _ hcop) a b

/-- Reducing modulo a polynomial `F` is invisible to the quotient map `R[X] → R[X] ⧸ (F)`:
`AdjoinRoot.mk F` (which *is* `Ideal.Quotient.mk (span {F})`) identifies `p` with `p %ₘ F`. -/
private theorem mk_modByMonic (F p : R[X]) :
    AdjoinRoot.mk F (p %ₘ F) = AdjoinRoot.mk F p := by
  rw [AdjoinRoot.mk_eq_mk, modByMonic_eq_sub_mul_div p F]
  exact ⟨-(p /ₘ F), by ring⟩

/--
**The incomplete-NTT component operation is `basemul`** (the §3 ↔ §1 bridge).

A single incomplete-NTT component is the quotient `R[X] ⧸ (X^2 - C ζ)` — the
`i`-th factor of the codomain of `incompleteNTT` for `f i = quadPoly ζ_i`.  This
quotient is definitionally `AdjoinRoot (quadPoly ζ)`, and on it the product of
two degree-`≤ 1` residues is exactly the schoolbook `basemul` of `basemul_mod`:

  `(a₀ + a₁ X)(b₀ + b₁ X) = (a₀ b₀ + ζ a₁ b₁) + (a₀ b₁ + a₁ b₀) X`.

So the pointwise multiplication that `incompleteNTT_map_mul` produces on each
quadratic component is precisely ML-KEM's `_poly_basemul`.
-/
theorem incompleteNTT_component_basemul (ζ a₀ a₁ b₀ b₁ : R) :
    (Ideal.Quotient.mk (Ideal.span {quadPoly ζ}) (C a₀ + C a₁ * X)
          * Ideal.Quotient.mk (Ideal.span {quadPoly ζ}) (C b₀ + C b₁ * X) :
        R[X] ⧸ Ideal.span {quadPoly ζ})
      = Ideal.Quotient.mk (Ideal.span {quadPoly ζ})
          (C (a₀ * b₀ + ζ * (a₁ * b₁)) + C (a₀ * b₁ + a₁ * b₀) * X) := by
  show AdjoinRoot.mk (quadPoly ζ) _ * AdjoinRoot.mk (quadPoly ζ) _
      = AdjoinRoot.mk (quadPoly ζ) _
  rw [← map_mul, ← basemul_mod, mk_modByMonic]

end CRT

end Negacyclic
end NTT
end CPolynomial
end CompPoly
